apiVersion: batch/v1
kind: CronJob
metadata:
  name: mailmaestro-trigger
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            image: curlimages/curl:7.85.0
            args:
              - -X
              - POST
              - http://mailmaestro.default.svc.cluster.local/run
          restartPolicy: OnFailure
          